### ISSUE TITLE
iOS InAppBrowser not responding to redirects

### ISSUE THREAD

**Issue by peterdemartini** [AppGyver/steroids#570]
There has been a recent update that broke the InAppBrowser events on iOS. They are no longer are responding some redirects. For example, 
	
	  var url = 'http://some-url-that-redirects-when-loaded.com'; // Should redirect to http://google.com
	  var newWindow = window.open(url, '_blank', 'location=no,toolbar=yes');

	  function exit() {
	    newWindow.removeEventListener('loadstart', loadStart);
	   	newWindow.removeEventListener('exit', exit);
	  }

	  function loadStart(e) {
	    console.log('URL : ', e.url);
	  }

	  newWindow.addEventListener('loadstart', loadStart);
	  newWindow.addEventListener('exit', exit);

Actual Output:

	URL : http://some-url-that-redirects-when-loaded.com

Correct Output:

	URL : http://some-url-that-redirects-when-loaded.com
	URL : http://google.com

This breaks my oauth login. I found this bug to only be present on iOS. All of the events for the `newWindow` seem to respond the same. Removing the toolbar or exit, also has no effect.

My testing was done in iOS 8.

**Comment by mitel** [comment]
looks like clearcache=yes work with iOS (was supposed to work only on Android..) - give it a try when you open the window:
var newWindow = window.open(url, '_blank', 'location=no,toolbar=yes,clearcache=yes');

**Comment by hcordray218** [comment]
That doesn't work for me on my scanner build using the latest version of the scanner (4.0.3-edge3)

**Comment by mitel** [comment]
yeah it's working for me with facebook redirects (iOS/scanner 4.0.20) and only if clearcache=yes.

**Comment by loban** [comment]
I'm facing the same problem. Doesn't work when using it for Google oAuth. The AppStore scanner and the custom debug scanner I build with latest edge version has the same problem: no event fired when the url changes from a redirect.

**Comment by loban** [comment]
Perhaps it's now been fixed?
https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-inappbrowser.git;a=commit;h=3f80b0b59c4ec45141fd66b2d723e427e2ca53ad

Is it possible to update the InAppBrowser cordova plugin (r0.5.4 released a few weeks ago) to a more recent version without having to wait for a steroids update?

**Comment by tiil** [comment]
Any news on this? Clearcache=yes doesn't fix it for me.

**Comment by chaitanyakhurana100** [comment]
clearcache=yes did the trick! Thanks..

**Comment by batuhan** [comment]
It's been months. It's not only the InAppBrowser. If I open a Modal with a redirect, same thing happens.

**Comment by pre** [comment]
InAppBrowser has now been updated to 0.5.4 in both Android and iOS clients. 

Please report here if it fixes this problem, thanks!

**Comment by Align-Deployment** [comment]
any news?

**Comment by tiil** [comment]
4.0.4-edge1 didn't resolve this for me.

**Comment by Align-Deployment** [comment]
@tiil I've got it working with 3.5.2 only.. ~>4.x doesn't work at all :(

**Comment by kaiserlos** [comment]
not working with 4.0.4 edge 1

**Comment by pre** [comment]
Hi, just checking in .. has any of you reported this issue to the InAppBrowser plugin's authors? They have a bug tracker: https://issues.apache.org/jira/browse/CB-6396?jql=text%20~%20%22inappbrowser%22

Could one of you, who is affected with this bug, please report this in the plugin's issue tracker? If the community plugin is updated, we are happy to merge in any updates. 

PS. If you have already reported this issue, please link it here so we could follow-up on its progress. Thank you!

**Comment by amrynsky** [comment]
Some additional information regarding this issue. InAppBrowser works fine on iOS emulator, but still doesn't work in AppGyver Scanner application. Probably it's somehow related to the webview and not to the InAppBrowser plugin.

AppGyver has a big advantage comparing to Ionic that most of Cordova plug-ins are available there out of the box. But I believe this is a blocker for most developers creating real apps on the AppGyver platform because it's not possible to use oAuth now. 

Thanks in advance.

**Comment by darknode** [comment]
I have the same issue.

**Comment by kaiserlos** [comment]
Just tested with the latest rc and it is still not working. I can't imagine that it is something plugin specific as many other pure cordova apps have oauth with inappbrowser working... 

This is really a blocker!

**Comment by s3lki3** [comment]
For the record, this issue has caused us to abandon AppGyver for our new version app development.  We're still forced to release with version 3.5.2.  Without the ability to connect via OAuth we can't operate.  

One workaround technique that we've started to try in the interim is to use the custom URL scheme, to open up the URL in the Safari app from our application.  When we're done with the connection, then redirect the user to the custom URL scheme that opens up our application.  This wouldn't work if you use 3rd party OAuth for user login, but if you're looking to connect something behind the scenes like we do, it has potential.

**Comment by andybbtt11** [comment]
Also blocked by this.

**Comment by harsaharsa** [comment]
We'll take another look at this, thanks for bumping!

**Comment by harsaharsa** [comment]
Alright, finally reproduced this. Seems to work fine on latest Android, but for some reason the InAppBrowser's location.href is not changed by the redirect, even though the correct content is rendered. This causes the event to not fire as well. We'll look into this ASAP.

**Comment by scicero1** [comment]
Thanks for looking into this. Also having this exact issue.

**Comment by harsaharsa** [comment]
Digging into this now. All the delegates etc are in place, but they're just not being called for some reason. Will keep you posted.

**Comment by kaiserlos** [comment]
Good that you'll look at it now!

**Comment by julianrockfish** [comment]
Also blocked by this !

**Comment by JesseCode** [comment]
Having the same issue - any luck? This is a huge block for me

**Comment by harsaharsa** [comment]
v4.0.5-edge1 from Build Service should fix this!

**Comment by andybbtt11** [comment]
Hmm, so far trying to build v4.0.5-edge1 gives me almost and instant email saying it failed with no error logs.  Build 4.0.4-edge3 works fine.

**Comment by harsaharsa** [comment]
Sorry, there was a hiccup – it's now fixed and should build fine (might take a bit longer than usual due to it being a new version that's not yet cached in all build service nodes).

**Comment by andybbtt11** [comment]
Build worked, however the inappbrowser is still behaving the same way for me. What I am trying to do is connect via a redirect_uri oauth flow WITHIN the inappbrowser. Basically just go to a website that uses a redirect and log in. This works in Android's inappbrowser. In iOS it is not changing the location.href or something and the oauth login page doesn't have it's styles or scripts.

**Comment by harsaharsa** [comment]
Alright, thanks for testing and sorry that the problem is still there – we'll take another look.

**Comment by andybbtt11** [comment]
Anyone else been having any luck with this?

**Comment by harsaharsa** [comment]
@andybbtt11 finally double-checked this, and you're right, there's still something weird going on. It's at the top of the backlog now, I'll keep you posted. Sorry for the wait.

**Comment by andybbtt11** [comment]
@harsaharsa Thanks.

**Comment by harsaharsa** [comment]
So I was a bit confused with what had been fixed, and currently the redirect events sent out by the InAppBrowser work fine, but the actual page `location.href` doesn't change. This is caused by some deep-rooted stuff on iOS (we intercept all HTTP requests to enable serving the app from localhost). You should be able to code your auth solution to work via the events – or is there some angle I missed here?

**Comment by s3lki3** [comment]
@harsaharsa For instance, if you are doing an OAuth2 authentication, say, Facebook.  When you see the facebook login screen, the browser is showing that form but the URL is your redirecting host (our own api, builds the token request and redirects you to do the auth).  The facebook login page won't accept a post from a foreign url and errors out, because to them it looks like i've created a duplicate login form that posts to theirs.  

So unless the location.href is correct, you can't proceed.  Other minor things happen like missing images as well because they are using relative urls on their pages, etc.

**Comment by andybbtt11** [comment]
@s3lki3 thank you, that is exactly my issue as well.

**Comment by Leeds-eBooks** [comment]
Can @s3lki3 or @andybbtt11 or anyone else confirm this is fixed in 4.0.5?

**Comment by andybbtt11** [comment]
I can't speak for the issue that was fixed with 4.0.5 but I can say that the issues that @s3lki3 laid out are still present and causing big problems for my company. We are unable to go through an external pages oauth flow within the inappbrowser, due to the location.href not being correct.  Works fine on Android.

**Comment by mojopollo** [comment]
I can confirm this is now correctly working on my scanner after npm updating steroids to 4.1.15

**Comment by s3lki3** [comment]
This is still not working for me in 4.1.15.  Can anyone else confirm that this is fixed?

**Comment by keithleung** [comment]
unfortunately to report that 4.1.15 still have this problem.

**Comment by andybbtt11** [comment]
It definitely does not work. 

The inAppBrowser events such as loadstart, loadend and close work fine. But the redirect within the inappbrowser is broken on iOS.

Using a url like:  http://{domain}.com/auth/oauth/authorize?response_type=token&client_id={redacted}&scope=profile&redirect_uri=http%3A%2F%2F{ourwebsite}.com

with the window.open( url, '_blank', 'location=yes') works exactly as expected in Android. but in iOS the page styles and scripts are not loaded and redirect after logging in does not work at all. This is what @s3lki3 detailed above. 

Not being able to implement a proper oauth with redirect_uri is really causing big problems for my team/company. On Android I am opening the window, waiting for access_token to be in the parms, then closing the window and applying the access token to my app. I am unable to do this with Apple. We have had to resort to using a password grant type api request to sign in, but this makes it so we are unable to authenticate other inappbrowsers/embeds in the app. We have a really annoying list of requirements and this is the only one we have been unable to meet.  My steroids, build, etc are all the newest version as of 9/18/2015.

I have already implemented the working solution in Android and it works as expected. Tagging @harsaharsa just so this thread isn't lost. Thanks.

Android (working):
![screenshot_2015-09-18-15-29-59](https://cloud.githubusercontent.com/assets/1443791/9970391/7e488022-5e1a-11e5-8029-053e6c1971d5.png)

Apple (broken):
![image1](https://cloud.githubusercontent.com/assets/1443791/9970534/449fee5e-5e1b-11e5-8e10-ab2b0ea4c02a.PNG)

**Comment by eschizoid** [comment]
Is somebody looking actively into this? This issues was marked as closed and is definitely not working.

**Comment by keithleung** [comment]
May I have a question that , is this bug is related on this case ?
https://github.com/AppGyver/steroids/issues/657

As Pre said InAppBrowser has now been updated to 0.5.4 in both Android and iOS client

But i round iOS InAppBrowser version is just 0.5.2 (Android is 0.5.4)
http://docs.appgyver.com/tooling/build-service/plugins/default-plugins/

How can I update the InAppBrowser plugin manually?

Thanks and sorry to by bad english

**Comment by keithleung** [comment]
One more information , as my teammate said  @andybbtt11 problem has been fixed on latest inappbrowser version (We simulate it on ionic).
May I have a question to @harsaharsa , Does it available to update inappbrowser plugin? I think the problem should be solved if Appgyver Inappbrowser package is updated :)  .

**Comment by harsaharsa** [comment]
Sorry for our unresponsiveness, and thanks for the detailed bug descriptions. They are apperciated. 

We're really trying to avoid messing with the age-old Cordova InAppBrowser any further. Instead, the plan is to create our own Supersonic "InAppBrowser" equivalent that would e.g. use the new SafariView on iOS 9 and have a much more maintainable codebase. I'll keep you posted on where that'll fall in the immediate backlog.

**Comment by Leeds-eBooks** [comment]
@harsaharsa That would be really fantastic, SafariView is what people will come to expect I think

**Comment by harsaharsa** [comment]
We actually figured out an underlying reason that was a relatively easy fix and didn't require many tweaks to the Cordova InAppBrowser – we'll have an edge version out that should fix this for good soon. Sorry for the slow response rate and grey hairs caused.

**Comment by andybbtt11** [comment]
::applauds:: Thanks @harsaharsa this will really help.

**Comment by jublo** [comment]
@harsaharsa Working on OAuth for our app right now—how long till we see a fix for this?

**Comment by eschizoid** [comment]
@harsaharsa Is there any estimate when the new release will come out?

**Comment by harsaharsa** [comment]
An 4.0.8-rc1 version is now available from the Build Service, sorry for the delay. It should fix this; please reply here if there's still any issues!

**Comment by jublo** [comment]
@harsaharsa What about the local CLI variant?

**Comment by harsaharsa** [comment]
The simulator update will come when we release 4.0.8 into stable (it's already in apple QA), so a few days more.

**Comment by jublo** [comment]
@harsaharsa Thanks! And after Apple shows green :vertical_traffic_light:, you'll release a new version of steroids-cli to npm?

**Comment by andybbtt11** [comment]
Can confirm here that it is working. Thanks again @harsaharsa

**Comment by eschizoid** [comment]
@harsaharsa thanks! working as expected.

**Comment by afixibiranchi** [comment]
I have installed the inappbrowser plugin from CLI as below:
$cordova plugin add cordova-plugin-inappbrowser

How to install the 4.0.8-rc1 version from the Build Service ?
Any url or so ?

**Comment by harsaharsa** [comment]
@afixibiranchi plugins work differently in Steroids, see http://docs.appgyver.com/tooling/build-service/plugins/

The InAppBrowser plugin (along with other Cordova core plugins) is included by default.

**Comment by leoSchmit** [comment]
Hi,

I'm trying to open a url A through InAppBrowser on a Cordova Windows app.
This url A is supposed to redirect to another url B.
The redirection seems not working and not being handled by this plugin on Windows plateform.
Would anyone have more information about InAppBrowser redirection ?

Thank you,
Leo

**Comment by yomencity** [comment]
@harsaharsa Hi I gave same error.
I use facebook account kit to verify phone number.
After I succeed in verifying phone number, redirection should occur. But nothing happen.
So, to solve this problem I want to follow your solution.
But I don't know how to install  the 4.0.8-rc1 version.
